kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
name: external-access
spec:
  podSelector:
   matchLabels:
     app: test1
   ingress:
   - ports:
     - protocol: TCP
       port: 8080
