apiVersion: policy.networking.k8s.io/v1alpha1
kind: AdminNetworkPolicy
metadata:
  name: block-untrusted
spec:
  priority: 100
  subject:
    namespaces:
     namespaceSelector: {}
  ingress:
    - name: deny-untrusted-ingress
      action: Deny
      from:
        - namespaces:
             matchLabels:
               untrusted: "true"
