kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: network-1-policy
spec:
  podSelector:
   matchLabels:
     deployment: test1
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          room: test200
      podSelector:
        matchLabels:
          deployment: test2
    ports:
    - port: 8080
      protocol: TCP

#allow incoming coonection only to pod with label  deployment=test1 from project with label room=test2 AND pod with label deployment=test2 only through the port 8080
